### ISSUE TITLE
New release for some safe-apps ( transaction builder...)

### ISSUE THREAD

**Issue by liliya-soroka** [gnosis/safe-react-apps#133]
New release for some safe-apps ( transaction builder...)
Compound app
WalletConnect app
Tx Builder App
Drain Account App

**Comment by liliya-soroka** [comment]
@francovenica , while testing some of the issues related to changes in Transaction builder, I updated our "Transaction builder"  test cases with additional cases. The cases contain contracts addresses that may be used for testing

**Comment by francovenica** [comment]
So I tried the test cases that Liliya left with some contracts there (Thanks Liliya)

- Tried the ETH field to send multiple ETH tx to accounts non-owners and owners.
- Tried queue tx where tx with eth were sent to a contract and a tx that would fail if executed. Even though the tx says it fails, the "send eth" action actually is executed (which is fine, check snapshot bellow)
- Tried and ERC20 contract to send Dai to several accounts and it worked fine
- Tried a Mintable token contract that works on rinkeby and minted some tokens: 0x029b4ec0e1a01bceffb64591b23315b1d81bd82a
- Checked the ETH field only shows for payable methods or for account addresses

Keep repeating these and queuing 6 or 7 tx at the same time checking they work. Also checking anything I could get my hands on, but on rinkeby there only so much you can do since contracts are just dummies

Didn't had issues, but Is hard to say that this will be 100% bug free. I will check it again in the regression


Snapshots
The tx failed because one of the actions was created to fail, but the action 1 was a "send eth" type of tx and that one went through fine
![image](https://user-images.githubusercontent.com/4503659/121788151-659ea100-cba1-11eb-8f12-22585745d394.png)
![image](https://user-images.githubusercontent.com/4503659/121788173-967ed600-cba1-11eb-8cbd-aedaa3728701.png)
