### ISSUE TITLE
[WalletConnect] If you switch safes, walletconnect keeps the same session

### ISSUE THREAD

**Issue by mikheevm** [gnosis/safe-react-apps#160]
## Description
When connecting a Dapp through wallet connect Safe App it creates a session between the dapp and the current safe. When changing the safe this is not detected an we still use the same wallet connect session that is stored in the localStorage, even it should be tied to the previous safe address.

## Steps to reproduce:
1. Connect via Safe 1 to any dApp that supports walletconnect
2. Switch to Safe 2 and navigate to wc safe app
3. Safe App displays the session from Safe 1

## Expected results
Sessions are determined by wallet address

### Obtained result
Session is used by both safes

**Comment by mikheevm** [comment]
Another option would be emitting `accountChanged` event:
https://docs.walletconnect.org/quick-start/dapps/web3-provider

https://gnosisinc.slack.com/archives/CQB729LLF/p1632921574107800

**Comment by anxolin** [comment]
Pasting my comment from slack, since it's related:

Hi, I just notice some small detail with the Gnosis Safe Wallet Connect app
Imagine you have safes A and B

If you:
* Are using safe A and connect using the WC app
* Then change to safe B
* The WC app shows the open connection that was created for A, but the Dapp still shows the Safe A although the safe B was created

I would expect the wallet to either emit a accountsChanged , if this is not an option for whatever reason, I would think that the safe B should have it’s own connection then.

https://docs.walletconnect.org/quick-start/dapps/web3-provider

![image](https://user-images.githubusercontent.com/2352112/135278226-a62f3dd3-9b3c-462d-96ea-265d7dcbc039.png)
