### ISSUE TITLE
DODO app not working on dev & staging

### ISSUE THREAD

**Issue by JagoFigueroa** [gnosis/safe-react-apps#186]
## Description
DODO app is not working on dev & staging environments.

## Environment
 - Environment: dev & staging (rinkeby)

## Steps to reproduce
 1. Open DODO app

## Expected result
Either App opens and is functional or remove it if it is not expected to work on these envs.

## Obtained result
![Screenshot 2021-11-09 at 12 30 43](https://user-images.githubusercontent.com/92332710/140918731-bf78e9b5-289d-4c1d-a89f-39723dafe563.png)

**Comment by dasanra** [comment]
We removed DODO app from dev & staging

**Comment by JagoFigueroa** [comment]
Does removal take a little bit more on staging @dasanra ? I am still able to see it on staging both on RInkeby and mainnet networks:

![Screenshot 2021-11-18 at 12 59 46](https://user-images.githubusercontent.com/92332710/142412452-7daa4744-babc-4a8d-a3b1-685d3f3c8bdb.png)

**Comment by dasanra** [comment]
@JagoFigueroa I forgot that staging web is now using PROD services :sweat_smile: 

If I remove it from here it will also be removed from PROD web. When we finally get the different staging/alpha environments for web staging web will use staging backend again, and alpha will be the one using PROD

In alpha this app won't be accessible anyway because they will still block based on domain, but PROD services.... so we can't remove it

**Comment by JagoFigueroa** [comment]
hahaha it's perfectly okay. I think we can close this ticket then.

Thank you @dasanra ;)
