### ISSUE TITLE
[TX-Builder] Allow custom contract data

### ISSUE THREAD

**Issue by dasanra** [gnosis/safe-react-apps#214]
## Overview
Currently in the Transaction Builder we only allow to create new transactions by selecting and filling the complete information after an ABI is provided and all fields are filled. Some users could prepare some custom data in some other dapp and just be willing to send it from the TX-Builder, for example sending a transaction where the signatures were gathered off chain

## Goals
We should allow switching to show custom hex encoded data the same way we allow it in contract interaction, either converting the user input to hex data or allowing to send custom hex data

## Requirements
- [ ] Allow input custom hex data to add a new transaction to the transaction builder
- [ ] Show custom hex data when user filled the different inputs when interacting with a smart contract

## Screens
Example in "Contract interaction" used as TX-Builder
![image](https://user-images.githubusercontent.com/25051234/143454190-7c1ae59a-429e-4816-952c-db1921d4bc61.png)

Example in "Contract interaction" of custom hex data transaction
![imagen](https://user-images.githubusercontent.com/25051234/143482260-0a2cedad-98eb-438a-a4dc-99a29f9d2b0b.png)

Any doubts we should check contract interaction feature on Safe web

**Comment by JagoFigueroa** [comment]
Hi there! Just to clarify @dasanra custom data is always expected to come with an {{asset}} value field regardless of the method used right? 

@yagopv made it so that instead of a required field it is now optional but it is different to the current implementation on web (which I really like but I mention this in case needs to be exactly the same. When no value is input, it will be understood as a 0 instead of being a required 0.

Current implementation when performing a contract interaction on web:

![Screenshot 2021-12-13 at 11 03 25](https://user-images.githubusercontent.com/92332710/145792321-9aaa9339-6aaf-4975-b6f5-f0ebbd1ce959.png)

Yagos approach on tx builder: 

![Screenshot 2021-12-13 at 11 03 48](https://user-images.githubusercontent.com/92332710/145792406-a31d3267-cb24-40c5-afb1-b9f5df252896.png)
