### ISSUE TITLE
[Tx builder] Missing icon tx history screen

### ISSUE THREAD

**Issue by JagoFigueroa** [gnosis/safe-react-apps#265]
## Description
The icon for this app is missing in a bunch of L2 chains (Optimism, Avalanche, Volta...) in prod environment

## Steps to reproduce
 1. Create and execute a tx using the app
 2. Go to Transactions history section

For reference: https://gnosis-safe.io/app/avax:0x480e5A3E90a3fF4a16AECCB5d638fAba96a15c28/transactions/history

## Expected result
Present app icon for every operation performed from the app

## Obtained result
Tx is present but missing app icon (+console error)

![Screenshot 2022-01-11 at 09 43 48](https://user-images.githubusercontent.com/92332710/148909605-d1c4e702-675b-489a-ac09-5c262c67403c.png)

**Comment by yagopv** [comment]
Could this be related to the application url coming in the history request from safe-web:

```
curl 'https://safe-client.gnosis.io/v1/chains/43114/safes/0x480e5A3E90a3fF4a16AECCB5d638fAba96a15c28/transactions/history' \
  --compressed
```

![image](https://user-images.githubusercontent.com/1576776/148978862-fb41a06b-4805-4c6a-88ba-c5a6083d3782.png)

the application url has a trailing slash. Is this configured when adding the app @dasanra ??

**Comment by yagopv** [comment]
@JagoFigueroa this is fixed with the change in the config Dani did the other day:

![image](https://user-images.githubusercontent.com/1576776/149546792-c2f33778-521b-4be0-881b-8369188780bb.png)

You need to create new transactions as past ones seems to come from a persistent storage

I only could get the same transaction history group with the correct safe app icon in prod and mainnet. In Rinkeby the result is the MultisendCall group with no clue about the safe app. Seems like a problem with the backend perhaps in certain networks.

**Comment by JagoFigueroa** [comment]
Gracias guys ;)
